name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install sphinx furo ghp-import sphinx-autodoc-typehints
      - run: cd docs && make html
      - run: ghp-import -n -p -f docs/build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
